name: bitsgap
description: A new Flutter project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  flutter:
    sdk: flutter
  flutter_mobx: ^2.1.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  json_annotation: ^4.8.1
  loggy: ^2.0.3
  mobx: ^2.2.0
  mobx_codegen: ^2.3.0
  mocktail: ^1.0.1
  overlay_support: ^2.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  bitsgap_analysis:
    path: ./packages/bitsgap_analysis
  build_runner: ^2.4.6
  dart_code_metrics: 5.7.2
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  json_serializable: ^6.6.2

fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf  

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

